import type { Lang } from "./types";

// Words for the screens people see before they're signed in (and the account page). The language
// comes from ?lang=en on these pages, since there's no account to read it from yet.

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://loro-ai.vercel.app";

const es = {
  welcomeBack: "¡Hola de nuevo!",
  loginIntro: "Entra para hacer tus facturas con la voz.",
  email: "Tu email",
  password: "Contraseña",
  newPassword: "Contraseña nueva",
  currentPassword: "Contraseña actual",
  passwordHint: "Mínimo 8 caracteres, con letras y números.",
  showPassword: "Mostrar",
  hidePassword: "Ocultar",
  signIn: "Entrar",
  signingIn: "Entrando…",
  forgot: "¿Olvidaste tu contraseña?",
  noAccount: "¿Todavía no tienes cuenta?",
  createAccount: "Crear cuenta",
  haveAccount: "¿Ya tienes cuenta?",
  signupTitle: "Crea tu cuenta",
  signupIntro: "Tu oficina en el bolsillo. Empiezas con 14 días de prueba gratis.",
  yourName: "Tu nombre",
  namePlaceholder: "Juan Hernández",
  creating: "Creando tu cuenta…",
  createButton: "Crear mi cuenta",
  inviteOnlyTitle: "Loro AI es por invitación, por ahora",
  inviteOnlyText: "Estamos abriendo poco a poco. Únete a la lista de espera y te mandamos tu invitación.",
  joinWaitlist: "Unirme a la lista de espera",
  invitedAs: "Invitación para",
  forgotTitle: "¿Olvidaste tu contraseña?",
  forgotText: "Todavía no mandamos correos desde Loro AI. Pídele a la persona que te invitó un enlace para cambiar tu contraseña. El enlace dura 48 horas y sirve una sola vez.",
  backToLogin: "Volver a entrar",
  resetTitle: "Elige una contraseña nueva",
  resetFor: "Para",
  resetButton: "Guardar y entrar",
  resetExpiredTitle: "Este enlace ya no sirve",
  resetExpiredText: "Los enlaces para cambiar la contraseña duran 48 horas y sirven una sola vez. Pide uno nuevo.",
  claimBanner: "¿Usabas la app antes de que existieran las cuentas?",
  claimLink: "Recupera tu cuenta",
  claimTitle: "Recupera tu cuenta",
  claimIntro: "Tus facturas de antes siguen aquí. Confirma la contraseña que usabas y elige tu email y una contraseña nueva. Esto se hace una sola vez.",
  oldPassword: "La contraseña que usabas antes",
  claimButton: "Recuperar mi cuenta",
  saved: "Guardado",
  save: "Guardar",
  english: "English",
  spanish: "Español",
  errors: {
    wrong_login: "El email o la contraseña no coinciden.",
    too_many: "Demasiados intentos. Espera 15 minutos y vuelve a intentar.",
    invalid_email: "Revisa el email: parece que le falta algo.",
    password_short: "La contraseña necesita al menos 8 caracteres.",
    password_weak: "Usa letras y números en la contraseña.",
    password_long: "La contraseña es demasiado larga.",
    name_missing: "Escribe tu nombre.",
    email_taken: "Ya existe una cuenta con ese email. Entra con tu contraseña.",
    invite_needed: "Necesitas una invitación para crear tu cuenta.",
    link_invalid: "Este enlace ya no sirve. Pide uno nuevo.",
    wrong_password: "La contraseña no es correcta.",
    nothing_to_claim: "No hay ninguna cuenta para recuperar.",
    generic: "Algo falló de nuestro lado. Intenta otra vez en un momento.",
  } as Record<string, string>,
};

export type AuthText = typeof es;

const en: AuthText = {
  welcomeBack: "Welcome back!",
  loginIntro: "Sign in to make your invoices by voice.",
  email: "Your email",
  password: "Password",
  newPassword: "New password",
  currentPassword: "Current password",
  passwordHint: "At least 8 characters, with letters and numbers.",
  showPassword: "Show",
  hidePassword: "Hide",
  signIn: "Sign in",
  signingIn: "Signing in…",
  forgot: "Forgot your password?",
  noAccount: "Don't have an account yet?",
  createAccount: "Create account",
  haveAccount: "Already have an account?",
  signupTitle: "Create your account",
  signupIntro: "Your office in your pocket. You start with a 14-day free trial.",
  yourName: "Your name",
  namePlaceholder: "John Smith",
  creating: "Creating your account…",
  createButton: "Create my account",
  inviteOnlyTitle: "Loro AI is invite-only for now",
  inviteOnlyText: "We're opening little by little. Join the waitlist and we'll send you an invitation.",
  joinWaitlist: "Join the waitlist",
  invitedAs: "Invitation for",
  forgotTitle: "Forgot your password?",
  forgotText: "Loro AI doesn't send emails yet. Ask the person who invited you for a link to change your password. The link lasts 48 hours and works once.",
  backToLogin: "Back to sign in",
  resetTitle: "Choose a new password",
  resetFor: "For",
  resetButton: "Save and sign in",
  resetExpiredTitle: "This link no longer works",
  resetExpiredText: "Password links last 48 hours and work once. Ask for a new one.",
  claimBanner: "Did you use the app before accounts existed?",
  claimLink: "Recover your account",
  claimTitle: "Recover your account",
  claimIntro: "Your earlier invoices are still here. Confirm the password you used and choose your email and a new password. You only do this once.",
  oldPassword: "The password you used before",
  claimButton: "Recover my account",
  saved: "Saved",
  save: "Save",
  english: "English",
  spanish: "Español",
  errors: {
    wrong_login: "That email and password don't match.",
    too_many: "Too many tries. Wait 15 minutes and try again.",
    invalid_email: "Check the email: something seems to be missing.",
    password_short: "The password needs at least 8 characters.",
    password_weak: "Use letters and numbers in the password.",
    password_long: "That password is too long.",
    name_missing: "Type your name.",
    email_taken: "There's already an account with that email. Sign in with your password.",
    invite_needed: "You need an invitation to create an account.",
    link_invalid: "This link no longer works. Ask for a new one.",
    wrong_password: "That password isn't right.",
    nothing_to_claim: "There's no account to recover.",
    generic: "Something failed on our side. Try again in a moment.",
  },
};

export const authText = (lang: Lang): AuthText => (lang === "en" ? en : es);
export const langParam = (v: string | string[] | undefined): Lang => (v === "en" ? "en" : "es");
export const errorText = (t: AuthText, code: string | undefined): string => t.errors[code ?? ""] ?? t.errors.generic;
