import type { Lang } from "./types";

// What Loro says on each setup step. Short, spoken style: one question per screen.

const es = {
  step: (n: number, of: number) => `Paso ${n} de ${of}`,
  back: "Atrás",
  next: "Siguiente",
  skip: "Saltar",
  start: "Empezar",
  hello: (name: string) => `¡Hola${name ? `, ${name}` : ""}! Soy Loro.`,
  helloText: "Te hago unas preguntas rápidas para que tus facturas salgan con tus datos. Son unos 2 minutos, y todo se puede cambiar después en Ajustes.",
  bizQ: "¿Cómo se llama tu negocio?",
  bizHint: "Así sale arriba en tus facturas.",
  bizLabel: "Nombre del negocio",
  bizPlaceholder: "Pintura Hernández",
  yourNameLabel: "Tu nombre",
  tradeQ: "¿A qué te dedicas?",
  tradeHint: "Así sé cómo escribir tus trabajos.",
  contactQ: "¿Cómo te contactan tus clientes?",
  contactHint: "Esto sale en tus facturas. Solo el teléfono y el email son importantes.",
  phone: "Teléfono",
  email: "Email",
  address: "Dirección (opcional)",
  website: "Sitio web (opcional)",
  phoneBad: "Escribe un teléfono de 10 dígitos.",
  emailBad: "Revisa el email.",
  whereQ: "¿En qué estado trabajas?",
  pickState: "Escoge tu estado",
  taxQ: "¿Cobras impuesto sobre la venta?",
  taxHint: "Muchos contratistas no lo cobran en la mano de obra. Si no sabes, pon «No»; lo puedes cambiar en cada factura.",
  yes: "Sí",
  no: "No",
  taxRate: "Porcentaje de impuesto",
  payQ: "¿Cómo te pagan?",
  payHint: "Escoge todas las que uses. Salen en la factura para que tu cliente sepa cómo pagarte.",
  payNeedOne: "Escoge al menos una forma de pago y llena sus datos.",
  dueQ: "¿Cuándo vence la factura?",
  dueNow: "Al recibirla",
  dueDays: (n: number) => `${n} días`,
  remindQ: "Si no te pagan, ¿cada cuánto le recuerdo?",
  remindNever: "No recordar",
  remindEvery: (n: number) => `Cada ${n} días`,
  voiceQ: "¿Cómo quieres que te hable?",
  voiceHint: "Escoge tu país y te hablo con su acento.",
  country: "País",
  woman: "Voz de mujer",
  man: "Voz de hombre",
  appLang: "Idioma de la app",
  saveAndGo: "Guardar",
  saving: "Guardando…",
  logoQ: "¿Tienes un logo?",
  logoHint: "Sale arriba en tus facturas. PNG o JPG, hasta 1 MB. Si no tienes, no pasa nada.",
  logoPick: "Subir mi logo",
  logoChange: "Cambiar logo",
  logoTooBig: "Ese archivo pesa más de 1 MB.",
  logoBadType: "Usa un PNG o JPG.",
  logoFailed: "No se pudo subir. Intenta otra vez.",
  doneTitle: "¡Listo! Ya estoy anotado.",
  doneText: "Ahora dime tu primera factura. Por ejemplo: «Factura para Juan, pintar la cocina, 2,200».",
  firstInvoice: "Hacer mi primera factura",
  saveFailed: "No se pudo guardar. Revisa tus datos e intenta otra vez.",
};

export type SetupText = typeof es;

const en: SetupText = {
  step: (n, of) => `Step ${n} of ${of}`,
  back: "Back",
  next: "Next",
  skip: "Skip",
  start: "Let's go",
  hello: (name) => `Hi${name ? `, ${name}` : ""}! I'm Loro.`,
  helloText: "A few quick questions so your invoices go out with your details. About 2 minutes, and you can change everything later in Settings.",
  bizQ: "What's your business called?",
  bizHint: "That's what goes at the top of your invoices.",
  bizLabel: "Business name",
  bizPlaceholder: "Smith Painting",
  yourNameLabel: "Your name",
  tradeQ: "What kind of work do you do?",
  tradeHint: "So I know how to write up your jobs.",
  contactQ: "How do customers reach you?",
  contactHint: "This goes on your invoices. Phone and email matter most.",
  phone: "Phone",
  email: "Email",
  address: "Address (optional)",
  website: "Website (optional)",
  phoneBad: "Type a 10-digit phone number.",
  emailBad: "Check the email.",
  whereQ: "Which state do you work in?",
  pickState: "Pick your state",
  taxQ: "Do you charge sales tax?",
  taxHint: "Many contractors don't charge it on labor. If you're not sure, pick “No”; you can change it on each invoice.",
  yes: "Yes",
  no: "No",
  taxRate: "Tax percent",
  payQ: "How do you get paid?",
  payHint: "Pick every one you use. They show on the invoice so your customer knows how to pay.",
  payNeedOne: "Pick at least one way to get paid and fill in its details.",
  dueQ: "When is the invoice due?",
  dueNow: "On receipt",
  dueDays: (n) => `${n} days`,
  remindQ: "If they don't pay, how often should I remind them?",
  remindNever: "Don't remind",
  remindEvery: (n) => `Every ${n} days`,
  voiceQ: "How should I talk to you?",
  voiceHint: "Pick your country and I'll talk with its accent.",
  country: "Country",
  woman: "Woman's voice",
  man: "Man's voice",
  appLang: "App language",
  saveAndGo: "Save",
  saving: "Saving…",
  logoQ: "Do you have a logo?",
  logoHint: "It goes at the top of your invoices. PNG or JPG, up to 1 MB. No logo is fine too.",
  logoPick: "Upload my logo",
  logoChange: "Change logo",
  logoTooBig: "That file is over 1 MB.",
  logoBadType: "Use a PNG or JPG.",
  logoFailed: "Couldn't upload it. Try again.",
  doneTitle: "All set! Got it all down.",
  doneText: "Now tell me your first invoice. For example: “Invoice for Juan, paint the kitchen, 2,200”.",
  firstInvoice: "Make my first invoice",
  saveFailed: "Couldn't save. Check your details and try again.",
};

export const setupText = (lang: Lang): SetupText => (lang === "en" ? en : es);
